"""adicionando o campo picture para o nome da imagem

Revision ID: e5c8f80c81eb
Revises: 450725ec079d
Create Date: 2026-05-22 01:06:28.311899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c8f80c81eb'
down_revision = '450725ec079d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=300), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('picture')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
