"""empty message

Revision ID: 38dbe32ad2ca
Revises: 
Create Date: 2026-04-16 21:36:32.607411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38dbe32ad2ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tempo_limite', sa.Integer(), nullable=True),
    sa.Column('memoria_limite', sa.Integer(), nullable=True),
    sa.Column('dificuldade', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('ranking', sa.String(length=5), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('submissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=False),
    sa.Column('linguagem', sa.String(length=30), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ACEITO', 'RESPOSTA_ERRADA', 'TEMPO_EXCEDIDO', 'ERRO_EXECUCAO', 'ERRO_COMPILACAO', name='statussubmissao'), nullable=False),
    sa.Column('tempo_execucao', sa.Integer(), nullable=True),
    sa.Column('memoria_usada', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['problema_id'], ['problema.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissao_problema_id'), ['problema_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissao_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissao_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=False),
    sa.Column('entrada', sa.Text(), nullable=False),
    sa.Column('saida_esperada', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['problema_id'], ['problema.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submissao_id', sa.Integer(), nullable=False),
    sa.Column('teste_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ACEITO', 'RESPOSTA_ERRADA', 'TEMPO_EXCEDIDO', 'ERRO_EXECUCAO', 'ERRO_COMPILACAO', name='statussubmissao'), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submissao_id'], ['submissao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teste_id'], ['teste.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultado_submissao_id'), ['submissao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultado_submissao_id'))

    op.drop_table('resultado')
    op.drop_table('teste')
    with op.batch_alter_table('submissao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissao_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_submissao_status'))
        batch_op.drop_index(batch_op.f('ix_submissao_problema_id'))

    op.drop_table('submissao')
    op.drop_table('user')
    op.drop_table('problema')
    # ### end Alembic commands ###
